# Assignment 1

**Due to**: 23/12/2021 (dd/mm/yyyy)

**Credits**: Andrea Galassi, Federico Ruggeri, Paolo Torroni

**Summary**: Part-of Speech (POS) tagging as Sequence Labelling using Recurrent Neural Architectures

# Intro

In this assignment  we will ask you to perform POS tagging using neural architectures

You are asked to follow these steps:
*   Download the corpora and split it in training and test sets, structuring a dataframe.
*   Embed the words using GloVe embeddings
*   Create a baseline model, using a simple neural architecture
*   Experiment doing small modifications to the baseline model, choose hyperparameters using the validation set
*   Evaluate your two best model
*   Analyze the errors of your model


**Task**: given a corpus of documents, predict the POS tag for each word

**Corpus**:
Ignore the numeric value in the third column, use only the words/symbols and its label. 
The corpus is available at:
https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip

**Splits**: documents 1-100 are the train set, 101-150 validation set, 151-199 test set.


**Features**: you MUST use GloVe embeddings as the only input features to the model.

**Splitting**: you can decide to split documents into sentences or not, the choice is yours.

**I/O structure**: The input data will have three dimensions: 1-documents/sentences, 2-token, 3-features; for the output there are 2 possibilities: if you use one-hot encoding it will be 1-documents/sentences, 2-token labels, 3-classes, if you use a single integer that indicates the number of the class it will be 1-documents/sentences, 2-token labels.

**Baseline**: two layers architecture: a Bidirectional LSTM layer and a Dense/Fully-Connected layer on top; the choice of hyper-parameters is yours.

**Architectures**: experiment using a GRU instead of the LSTM, adding an additional LSTM layer, and adding an additional dense layer; do not mix these variantions.


**Training and Experiments**: all the experiments must involve only the training and validation sets.

**Evaluation**: in the end, only the two best models of your choice (according to the validation set) must be evaluated on the test set. The main metric must be F1-Macro computed between the various part of speech. DO NOT CONSIDER THE PUNCTUATION CLASSES.

**Metrics**: the metric you must use to evaluate your final model is the F1-macro, WITHOUT considering punctuation/symbols classes; during the training process you can use accuracy because you can't use the F1 metric unless you use a single (gigantic) batch because there is no way to aggregate "partial" F1 scores computed on mini-batches.

**Discussion and Error Analysis** : verify and discuss if the results on the test sets are coherent with those on the validation set; analyze the errors done by your model, try to understand which may be the causes and think about how to improve it.

**Report**: you are asked to deliver the code of your experiments and a small pdf report of about 2 pages; the pdf must begin with the names of the people of your team and a small abstract (4-5 lines) that sums up your findings.

# Out Of Vocabulary (OOV) terms

How to handle words that are not in GloVe vocabulary?
You can handle them as you want (random embedding, placeholder, whatever!), but they must be STATIC embeddings (you cannot train them).

But there is a very important caveat! As usual, the element of the test set must not influence the elements of the other splits!

So, when you compute new embeddings for train+validation, you must forget about test documents.
The motivation is to emulate a real-world scenario, where you select and train a model in the first stage, without knowing nothing about the testing environment.

For implementation convenience, you CAN use a single vocabulary file/matrix/whatever. The principle of the previous point is that the embeddings inside that file/matrix must be generated independently for train and test splits.

Basically in a real-world scenario, this is what would happen:
1. Starting vocabulary V1 (in this assignment, GloVe vocabulary)
2. Compute embeddings for terms out of vocabulary V1 (OOV1) of the training split 
3. Add embeddings to the vocabulary, so to obtain vocabulary V2=V1+OOV1
4. Training of the model(s)
5. Compute embeddings for terms OOV2 of the validation split 
6. Add embeddings to the vocabulary, so to obtain vocabulary V3=V1+OOV1+OOV2
7. Validation of the model(s)
8. Compute embeddings for terms OOV3 of the test split 
9. Add embeddings to the vocabulary, so to obtain vocabulary V4=V1+OOV1+OOV2+OOV3
10. Testing of the final model

In this case, where we already have all the documents, we can simplify the process a bit, but the procedure must remain rigorous.

1. Starting vocabulary V1 (in this assignment, GloVe vocabulary)
2. Compute embeddings for terms out of vocabulary V1 (OOV1) of the training split 
3. Add embeddings to the vocabulary, so to obtain vocabulary V2=V1+OOV1
4. Compute embeddings for terms OOV2 of the validation split 
5. Add embeddings to the vocabulary, so to obtain vocabulary V3=V1+OOV1+OOV2
6. Compute embeddings for terms OOV3 of the test split 
7. Add embeddings to the vocabulary, so to obtain vocabulary V4=V1+OOV1+OOV2
8. Training of the model(s)
9. Validation of the model(s)
10. Testing of the final model

Step 2 and step 6 must be completely independent of each other, for what concerns the method and the documents. But they can rely on the previous vocabulary (V1 for step 2 and V3 for step 6)
THEREFORE if a word is present both in the training set and the test split and not in the starting vocabulary, its embedding is computed in step 2) and it is not considered OOV anymore in step 6).

# Report
The report must not be just a copy and paste of graphs and tables!

The report must not be longer than 2 pages and must contain:
* The names of the member of your team
* A short abstract (4-5 lines) that sum ups everything
* A general description of the task you have addressed and how you have addressed it
* A short description of the models you have used
* Some tables that sum up your findings in validation and test and a discussion of those results
* The most relevant findings of your error analysis

# Evaluation Criterion

The goal of this assignment is not to prove you can find best model ever, but to face a common task, structure it correctly, and follow a correct and rigorous experimental procedure.
In other words, we don't care if you final models are awful as long as you have followed the correct procedure and wrote a decent report.

The score of the assignment will be computed roughly as follows
* 1 point for the general setting of the problem
* 1 point for the handling of OOV terms
* 1 point for the models
* 1 point for train-validation-test procedure
* 2 point for the discussion of the results, error analysis, and report

This distribution of scores is tentative and we may decide to alter it at any moment.
We also reserve the right to assign a small bonus (0.5 points) to any assignment that is particularly worthy. Similarly, in case of grave errors, we may decide to assign an equivalent malus (-0.5 points).

# Contacts

In case of any doubt, question, issue, or help we highly recommend you to check the [course useful material](https://virtuale.unibo.it/pluginfile.php/1036039/mod_resource/content/2/NLP_Course_Useful_Material.pdf) for additional information, and to use the Virtuale forums to discuss with other students.

You can always contact us at the following email addresses. To increase the probability of a prompt response, we reccomend you to write to both the teaching assistants.

Teaching Assistants:

* Andrea Galassi -> a.galassi@unibo.it
* Federico Ruggeri -> federico.ruggeri6@unibo.it

Professor:

* Paolo Torroni -> p.torroni@unibo.it


# FAQ
* You can use a non-trainable Embedding layer to load the glove embeddings
* You can use any library of your choice to implement the networks. Two options are tensorflow/keras or pythorch. Both these libraries have all the classes you need to implement these simple architectures and there are plenty of tutorials around, where you can learn how to use them.

In [1]:
import os, shutil  #  file management
import sys 
import pandas as pd  #  dataframe management
import numpy as np  #  data manipulation

In [2]:
import urllib.request  #  download files
import zipfile  #  unzip files
import nltk
import tensorflow as tf
from tensorflow import keras

In [6]:
dataset_folder = os.path.join(os.getcwd(), "Datasets", "Original")

if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

url = 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip'

dataset_path = os.path.join(dataset_folder, "treebank.zip")

if not os.path.exists(dataset_path):
    urllib.request.urlretrieve(url, dataset_path)
    print("Successful download")

with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(dataset_folder)
print("Successful extraction")

Successful download
Successful extraction


In [7]:
dataset_name = "dependency_treebank"


folder = os.path.join(os.getcwd(), "Datasets", "Original", dataset_name)

pre_train = []
pre_valid = []
pre_test = []
i = 1

file_list = sorted(os.listdir(folder))

for filename in file_list:
  file_path = os.path.join(folder, filename)
  if os.path.isfile(file_path):
    # open the file
      text = []
      with open(file_path, mode='r', encoding='utf-8') as text_file:
        text = text_file.read()
        if i <= 100:
          pre_train.append(text)
        elif i <= 150:
          pre_valid.append(text)
        else:
          pre_test.append(text)  
  i+=1

tr = []
val = []
tes = []

for paragraph in pre_train:
   tr.append(paragraph.split('\n'))
for paragraph in pre_valid:
   val.append(paragraph.split('\n'))
for paragraph in pre_test:
   tes.append(paragraph.split('\n'))


In [8]:
train = []
valid = []
test = []

for i in tr:
  for j in i:
    train.append(j.split('\t'))

for i in val:
  for j in i:
    valid.append(j.split('\t'))

for i in tes:
  for j in i:
    test.append(j.split('\t'))

In [9]:
train_sentences = []
valid_sentences = []
test_sentences = []
train_tags = []
valid_tags = []
test_tags = []

s = []
t = []
for i in train:
  if i[0] != '':
    s.append(i[0])
    t.append(i[1])
  else:
    train_sentences.append(s)
    train_tags.append(t)
    s = []
    t = []

s = []
t = []
for i in valid:
  if i[0] != '':
    s.append(i[0])
    t.append(i[1])
  else:
    valid_sentences.append(s)
    valid_tags.append(t)
    s = []
    t = []

s = []
t = []
for i in test:
  if i[0] != '':
    s.append(i[0])
    t.append(i[1])
  else:
    test_sentences.append(s)
    test_tags.append(t)
    s = []
    t = []

In [10]:
flat_train = [item for sublist in train_sentences for item in sublist]
flat_valid = [item for sublist in valid_sentences for item in sublist]
flat_test = [item for sublist in test_sentences for item in sublist]

In [11]:
from tensorflow.keras.layers import TextVectorization

vectorizer = TextVectorization(max_tokens=20000, output_sequence_length=200)
text_ds_train = tf.data.Dataset.from_tensor_slices(flat_train).batch(128)
text_ds_valid = tf.data.Dataset.from_tensor_slices(flat_valid).batch(128)
text_ds_test = tf.data.Dataset.from_tensor_slices(flat_test).batch(128)

vectorizer.adapt(text_ds_train)
voc_train = vectorizer.get_vocabulary()

vectorizer.adapt(text_ds_valid)
voc_valid = vectorizer.get_vocabulary()

vectorizer.adapt(text_ds_test)
voc_test = vectorizer.get_vocabulary()

In [12]:
print(len(voc_train))
voc_train += list(set(voc_valid) - set(voc_train))
print(len(voc_train))
voc_train += list(set(voc_test) - set(voc_train))
print(len(voc_train))

7306
9733
10736


In [13]:
word_index = dict(zip(voc_train, range(2, len(voc_train)+3)))
word_index['-PAD-'] = 0
word_index['-OOV-'] = 1

tags = set([item for sublist in train_tags for item in sublist])

tag2index = {t: i + 1 for i, t in enumerate(tags)}
tag2index['-PAD-'] = 0 

In [14]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

--2021-12-02 15:24:43--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2021-12-02 15:24:43--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2021-12-02 15:24:43--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [15]:
path_to_glove_file = os.path.join(os.getcwd(), "glove.6B.100d.txt")

embeddings_index = {}
with open(path_to_glove_file) as f:
    for line in f:
        word, coefs = line.split(maxsplit=1)
        coefs = np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word] = coefs

print("Found %s word vectors." % len(embeddings_index))


Found 400000 word vectors.


In [16]:
num_tokens = len(voc_train) + 2
embedding_dim = 100
hits = 0
misses = 0


# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
    else:
        embedding_matrix += np.random.uniform(low=-0.05, high=0.05, size=embedding_dim)
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

Converted 9753 words (985 misses)


In [17]:
from tensorflow.keras.layers import Embedding

embedding_layer = Embedding(
    num_tokens,
    embedding_dim,
    embeddings_initializer=keras.initializers.Constant(embedding_matrix),
    trainable=False,
)

In [18]:
MAX_LENGTH = len(max(train_sentences, key=len))
print(MAX_LENGTH)

249


In [19]:
train_sentences_X, valid_sentences_X, test_sentences_X, train_tags_y, valid_tags_y, test_tags_y = [], [], [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word_index[w.lower()])
        except KeyError:
            s_int.append(word_index['-OOV-'])
 
    train_sentences_X.append(s_int)

for s in valid_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word_index[w.lower()])
        except KeyError:
            s_int.append(word_index['-OOV-'])
 
    valid_sentences_X.append(s_int)

for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word_index[w.lower()])
        except KeyError:
            s_int.append(word_index['-OOV-'])
 
    test_sentences_X.append(s_int)
 
for s in train_tags:
    train_tags_y.append([tag2index[t] for t in s])

for s in valid_tags:
    valid_tags_y.append([tag2index[t] for t in s])
 
for s in test_tags:
    test_tags_y.append([tag2index[t] for t in s])

In [20]:
from keras.preprocessing.sequence import pad_sequences
 
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
valid_sentences_X = pad_sequences(valid_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
valid_tags_y = pad_sequences(valid_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')

In [21]:
!pip install -U keras

In [26]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation
from tensorflow.keras.optimizers import Adam
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(embedding_layer)
model.add(Bidirectional(LSTM(256, return_sequences=True)))
model.add(LSTM(256, return_sequences=True))
model.add(Dense(len(tag2index)))
model.add(Activation('relu'))
 
model.compile(loss='categorical_crossentropy',
             optimizer=Adam(0.001),
             metrics=['accuracy'])
 
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 249, 100)          1073800   
                                                                 
 bidirectional_1 (Bidirectio  (None, 249, 512)         731136    
 nal)                                                            
                                                                 
 lstm_3 (LSTM)               (None, 249, 256)          787456    
                                                                 
 dense_1 (Dense)             (None, 249, 46)           11822     
                                                                 
 activation_1 (Activation)   (None, 249, 46)           0         
                                                                 
Total params: 2,604,214
Trainable params: 1,530,414
Non-trainable params: 1,073,800
____________________________________

In [27]:
def to_categorical(sequences, categories):
    cat_sequences = []
    for s in sequences:
        cats = []
        for item in s:
            cats.append(np.zeros(categories))
            cats[-1][item] = 1.0
        cat_sequences.append(cats)
    return np.array(cat_sequences)

In [28]:
cat_train_tags_y = to_categorical(train_tags_y, len(tag2index))
print(cat_train_tags_y[0])

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [29]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=128, epochs=40, validation_data=(valid_sentences_X, to_categorical(valid_tags_y, len(tag2index))))

Epoch 1/40
16/16 [==============================] - 156s 9s/step - loss: 3.3099 - accuracy: 0.7276 - val_loss: 1.1278 - val_accuracy: 0.9036
Epoch 2/40
16/16 [==============================] - 146s 9s/step - loss: 1.0847 - accuracy: 0.9031 - val_loss: 0.9321 - val_accuracy: 0.9036
Epoch 3/40
16/16 [==============================] - 147s 9s/step - loss: 0.8885 - accuracy: 0.9031 - val_loss: 0.8515 - val_accuracy: 0.9036
Epoch 4/40
16/16 [==============================] - 148s 9s/step - loss: 0.7714 - accuracy: 0.9031 - val_loss: 0.7560 - val_accuracy: 0.9036
Epoch 5/40
16/16 [==============================] - 150s 9s/step - loss: 0.7441 - accuracy: 0.9031 - val_loss: 0.7453 - val_accuracy: 0.9036
Epoch 6/40
16/16 [==============================] - 153s 10s/step - loss: 0.7935 - accuracy: 0.9031 - val_loss: 0.7410 - val_accuracy: 0.9036
Epoch 7/40
16/16 [==============================] - 152s 10s/step - loss: 0.7074 - accuracy: 0.9031 - val_loss: 0.9120 - val_accuracy: 0.9036
Epoch 8/40
